CREATE TABLE IF NOT EXISTS tokens_scopes (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  token_id int UNSIGNED NOT NULL,
  scope varchar(128) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (token_id) REFERENCES tokens(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (scope) REFERENCES scopes(name) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = innodb DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;